services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BackendTarget:-dev}
      args:
        AppEnvironment: ${AppEnvironment:-live}
        BuildNumber: ${BuildNumber:-local}
        BuildId: ${BuildId:-local}
        BuildUser: ${BuildUser:-local}
    container_name: transcriptions-backend
    ports:
      - "8000:80"
    networks:
      - transcription-shared

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${FrontendTarget:-dev}
      args:
        AppEnvironment: ${AppEnvironment:-live}
        BuildNumber: ${BuildNumber:-local}
        BuildId: ${BuildId:-local}
        BuildUser: ${BuildUser:-local}
    container_name: transcriptions-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - transcription-shared

networks:
  transcription-shared:
    external: true
