"""add_transcript_indexes

Revision ID: 00
Revises: 
Create Date: 2026-03-20 11:44:18.895389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_details_t',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('begin_timestamp', sa.String(length=50), nullable=True),
    sa.Column('end_timestamp', sa.String(length=50), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('users_t',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=215), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_t', schema='public')
    op.drop_table('transcript_details_t', schema='public')
    # ### end Alembic commands ###
