CREATE TABLE public.users_t (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    unique_id VARCHAR(50),
    user_email VARCHAR(215),
    user_name VARCHAR(200),
    first_name VARCHAR(200),
    last_name VARCHAR(100),
    display_name VARCHAR(200),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by INTEGER NOT NULL,
    modified TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

